### ISSUE TITLE
Add the icon of rating and review

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Ravenous#11]
Feature Requested : -  Please add the **ICON** of `Rating` , `Review` and `Location`

![image](https://user-images.githubusercontent.com/41269164/70090548-69fb0d00-1640-11ea-8124-7806a8ed6428.png)

**Comment by sgpritam** [comment]
@rajat2502 Please review the issue

**Comment by rajat2502** [comment]
Go ahead!!!

**Comment by abhisheknaiidu** [comment]
@rajat2502 I have made some changes. you can check -

https://github.com/NJACKWinterOfCode/Ravenous/pull/15#issue-353071417

![raven](https://user-images.githubusercontent.com/55599878/70832165-69216280-1e1a-11ea-87a5-915b96b06143.png)
