### ISSUE TITLE
Improve the design of the business component

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/Ravenous#14]
Improving the CSS and adding some animations to make the UX better.

**Comment by ankushbhardwxj** [comment]
@rajat2502 I would like to work on it. Please assign me to it.

**Comment by rajat2502** [comment]
Cool!!! Go Ahead.

**Comment by rajat2502** [comment]
Are you working?

**Comment by ankushbhardwxj** [comment]
@rajat2502 yes, actually due to problems in assam, govt had cut off internet connection completely. Will be making a PR soon

**Comment by rajat2502** [comment]
Okay
