### ISSUE TITLE
Display Random Background Picture

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/Ravenous#21]
Currently, we have only 1 background picture of the project, which is very monotonous. We could fetch a new picture from some API so that every time user opens the page, they get to see a new picture.

**Comment by ankushbhardwxj** [comment]
@rajat2502 what do you think about this ?

**Comment by rajat2502** [comment]
Well that would be hard to judge which image will suite the theme and which not.

**Comment by ankushbhardwxj** [comment]
I understand, the Yelp website has a similar feature. We can use the Yelp API itself for it. See here https://www.yelp.com/ .We should think about making some changes to the header and footer accordingly. They look really basic.

**Comment by rajat2502** [comment]
Okay go ahead!!!
