### ISSUE TITLE
Add Some Footer Content

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Ravenous#3]
Please add some footer content in homepage
Footer content
     1. Facebook
      2. Twitter
      3. About

![Capture](https://user-images.githubusercontent.com/41269164/69904949-ab3ab500-13d3-11ea-8c5d-b6e5d9df4da9.PNG)

@rajat2502 Please review the issue

**Comment by ankushbhardwxj** [comment]
@rajat2502 I can try my hand at designing the footer. Assign me this 👍

**Comment by abhisheknaiidu** [comment]
@rajat2502 Added a new Footer, you can check #16
