### ISSUE TITLE
Current location

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Ravenous#5]
When the user move one place to another place then he/she can't search anytime current location.Automatically it changes to current location.
`Add the current Location Feature`

**Comment by rajat2502** [comment]
Looks Good to me!!! Should I assign it to you?

**Comment by sgpritam** [comment]
Yes

**Comment by ankushbhardwxj** [comment]
@rajat2502 Is @sgpritam still working on this ? If not, I'd like to get this done 👍

**Comment by sgpritam** [comment]
Yes working on it

**Comment by ankushbhardwxj** [comment]
@sgpritam did you get this done ? If not, please let me work on it.

**Comment by sgpritam** [comment]
Bro i am currently working on it

**Comment by ankushbhardwxj** [comment]
Since there hasn't been any update for long, I've worked this out.
