### ISSUE TITLE
Image missing 

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Ravenous#6]
When you type in searchbar `Search Business = food` ` Where ? = Delhi` some image are missing

![imgmiss](https://user-images.githubusercontent.com/41269164/69906314-b3045480-13e7-11ea-8927-895463feb754.PNG)

**Comment by rajat2502** [comment]
@sgpritam the data comes from Yelp's API so maybe they don't have such images. You can try other locations like London then all the images are there.
